name: Bazel Build

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Bazel target to build'
        required: true
        default: '//:demo'
        type: string
      test_target:
        description: 'Bazel test target'
        required: false
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Bazel
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt-get update
        sudo apt-get install -y bazel

    - name: Build
      run: |
        bazel build ${{ github.event.inputs.target }}

    - name: Test
      if: ${{ github.event.inputs.test_target != '' }}
      run: |
        bazel test ${{ github.event.inputs.test_target }}