name: Clang-Tidy Code Analysis

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type for analysis'
        required: true
        default: 'Debug'
        type: choice
        options:
        - Debug
        - Release

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang-tidy

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

    - name: Run Clang-Tidy
      run: |
        cd build
        # Run clang-tidy on all source files
        find ../src -name "*.cpp" -exec clang-tidy {} -p . \; || true

    - name: Upload analysis results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: clang-tidy-results-${{ inputs.build_type }}
        path: |
          build/
        retention-days: 30